export const Action = {
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
  SET_FILTERS: "SET_FILTERS",
  SET_DELETE_PRODUCTS_DIALOG: "SET_DELETE_PRODUCTS_DIALOG",
  SET_SELECTED_ROWS: "SET_SELECTED_ROWS",
  SET_DELETE_PRODUCT_DIALOG: "SET_DELETE_PRODUCT_DIALOG",
  SET_ROW_DELETED: "SET_ROW_DELETED",

  CREATE_USER: "CREATE_USER",
  SET_ID: "SET_ID",
  SET_DATA: "SET_DATA",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_FIELD: "UPDATE_FIELD",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_IS_SUBMITTING: "SET_IS_SUBMITTING",
  // SET_ERROR: "SET_ERROR",

  // UPDATE_FIELD: "UPDATE_FIELD",
  // SUBMIT_FORM: "SUBMIT_FORM",
  // DELETE_ITEM: "DELETE_ITEM",
  // SET_EDIT_INDEX: "SET_EDIT_INDEX",
};

// export const CREATE_USER = "CREATE_USER";
// export const UPDATE_USER = "UPDATE_USER";
// export const DELETE_USER = "DELETE_USER";
// export const UPDATE_FIELD = "UPDATE_FIELD";
// export const SET_ID = "SET_ID";
// export const SET_DATA = "SET_DATA";
// export const UPDATE_ERRORS = "UPDATE_ERRORS";
// export const SET_LOADING = "SET_LOADING";
// export const SET_IS_SUBMITTING = "SET_IS_SUBMITTING";
// export const SET_ERROR = "SET_ERROR";
